### ISSUE TITLE
Bridles details

### ISSUE THREAD

**Issue by platipusica** [wingworks/Ventus-8#1]
Hi Karsten

this might be of some value to others as well, are the bridles length information somehow included in the project? 
Thanks!
D.

**Comment by wingworks** [comment]
Hi,
you can find all information about the bridle in the ## Bridle ## section in the  [Ventus-S.kite](https://github.com/wingworks/Ventus-S/blob/master/Ventus_S.kite) file and in the 3D blender kite model.

Karsten
